Lesson1
MaksimKuzur/webix-start pull request #1
Opened 2021-09-23 10:08 UTC by MaksimKuzur

the version V1.0 of the application "MyFirstApp" was created

2021-09-23 10:46 UTC, igr-ik commented on myFirstApp.html
> +	<style type="text/css">
Стили лучше вынести в отдельный файл

2021-09-23 10:46 UTC, igr-ik commented on myFirstApp.html
> +        .labelMyApp{
Классы в css принято писать разделяя слова, не в camelCase стиле, например: label-my-app или label_my_app.
Так же старайся давать более осознанные названия классам, нежели просто label-my-app, не понятно что имеется под my-app.

2021-09-23 10:46 UTC, igr-ik commented on myFirstApp.html
> +	<script type="text/javascript" charset="utf-8">
javascript код тоже вынеси в отдельный файл и подключи его здесь в body.

2021-09-23 10:46 UTC, igr-ik commented on myFirstApp.html
> +        var listLeft = {
Забудь про var, используй let если значения переменной будет изменяться, и const если значения будет статичным, не изменять в ходе выполнения всей программы. В данном случае подойдет const.
И названия переменным давай тоже осознанные, чтобы прочитав его было понятно что в нем содержится. По listLeft не понятно что здесь. Понятно что список, но какой левый список? Список чего? Здесь просто подошло бы menu.

2021-09-23 10:46 UTC, igr-ik commented on myFirstApp.html
> +        var dataCol2 = {
Попробуй сам, по названию переменной dataCol2 сказать что в ней содержится, не смотря на присвоения.

2021-09-23 10:46 UTC, igr-ik commented on myFirstApp.html
> +        var toolBarRi = {
Опять, toolBarRi не понятно что здесь. И старайся слова писать полностью, без сокращения. Что такое Ri?
Подправь пожалуйста, именования переменных по всему коду.

2021-09-23 10:46 UTC, igr-ik commented on myFirstApp.html
> +                { view:"button", value:"Add new", css:"webix_primary", width:105},
Не экономь место, удобнее читать код, когда свойства объекта начинаются с новой строки. Не нужно вмещать объект в одну строку.

2021-09-23 16:27 UTC, HelgaListopad requested changes

2021-09-23 16:27 UTC, HelgaListopad commented on myFirstApp.html
> +            view:"button",
Здесь запланирован просто некликабельный текст, поэтому есть смысл переделать на label/template
В этом случае не придётся стилизовать отдельными стилями текст и иконку (сейчас у неё нет стиля вообще)

2021-09-23 16:27 UTC, HelgaListopad commented on myFirstApp.html
> +                { view:"button", value:"Clear", width:105 },
Ширину кнопок не надо подгонять под ширину формы - они сами займут доступное место
Другое дело, что доступное место стараются занять и spacer'ы - здесь это излишне.
Удобнее задать для cols 
- `margin` для отступа между кнопками 
- и `padding` (или `paddingX`) для отступа от краёв

2021-09-23 16:27 UTC, HelgaListopad commented on myFirstApp.html
> +            css:"buttonTop",
Цвет текста заменён, а вот цвет иконки - нет. 
Это вопрос правильного css-селектора для неё (выясняется через инспектор).
Например, `.buttonTop .webix_button .webix_icon_btn`

2021-09-23 20:47 UTC, MaksimKuzur commented on myFirstApp.html
> +	<style type="text/css">
сделано

2021-09-23 20:47 UTC, MaksimKuzur commented on myFirstApp.html
> +        .labelMyApp{
исправлено

2021-09-23 20:47 UTC, MaksimKuzur commented on myFirstApp.html
> +	<script type="text/javascript" charset="utf-8">
сделано

2021-09-23 20:47 UTC, MaksimKuzur commented on myFirstApp.html
> +        var listLeft = {
исправлено

2021-09-23 20:47 UTC, MaksimKuzur commented on myFirstApp.html
> +            view:"button",
исправлено

2021-09-23 20:47 UTC, MaksimKuzur commented on myFirstApp.html
> +        var dataCol2 = {
исправлено

2021-09-23 20:47 UTC, MaksimKuzur commented on myFirstApp.html
> +        var toolBarRi = {
исправлено

2021-09-23 20:47 UTC, MaksimKuzur commented on myFirstApp.html
> +                { view:"button", value:"Add new", css:"webix_primary", width:105},
исправлено

2021-09-23 20:47 UTC, MaksimKuzur commented on myFirstApp.html
> +                { view:"button", value:"Clear", width:105 },
исправлено

2021-09-23 20:47 UTC, MaksimKuzur commented on myFirstApp.html
> +            css:"buttonTop",
исправлено

2021-09-24 07:23 UTC, igr-ik approved these changes

2021-09-24 08:07 UTC, HelgaListopad approved these changes

2021-09-24 09:51 UTC, merged