Lesson2
MaksimKuzur/webix-start pull request #2
Opened 2021-09-24 09:01 UTC by MaksimKuzur

lesson2 job done

2021-09-24 10:25 UTC, HelgaListopad requested changes

2021-09-24 10:25 UTC, HelgaListopad commented on script.js
> +    width:250,
Ширины формы уже не хватает для корректного отображения invalidMessage
По базовому дизайну это всегда однострочный текст, поэтому нужно либо его сократить, либо увеличить ширину формы

2021-09-24 10:25 UTC, HelgaListopad commented on script.js
> +        { view:"text", label:"Title", name:"title", invalidMessage:"“title“ must be filled in" },
Если нужны кавычки, их можно просто экранировать

2021-09-24 10:25 UTC, HelgaListopad commented on script.js
> +            view:"fieldset",
fieldset - это контейнер с заголовком для других вьюшек
Если нужен только заголовок - лучше использовать section template
https://docs.webix.com/desktop__template.html#templatetypes

2021-09-24 10:25 UTC, HelgaListopad commented on script.js
> +                if($$("formInputElements").validate()){
Чуть теряется смысл названий
Форма у тебя одна - и у неё ID formInputElements
Кнопки по структуре к форме уже не имеют никакого отношения, но судя по ID должны к ней принадлежать

Из-за этого можно потом позже запутаться, поэтому я предлагаю
- изменить ID формы
- вложить `formToolbar` в её elements

Кроме того, если ты так сделаешь, у тебя появится возможность получить форму не только по её ID, но и с помощью метода `$$("button").getFormView()`

2021-09-24 10:25 UTC, HelgaListopad commented on script.js
> +            y:40
разумнее привязаться к координатам кнопки - можно своими расчётами (сложно), а можно просто `popup.show(button.getNode())`

2021-09-24 10:25 UTC, HelgaListopad commented on script.js
> +    move:true,
А зачем и работает ли?..

2021-09-24 10:50 UTC, igr-ik commented on script.js
> +            click:function() {
Здесь можно просто использовать метод объекта, без function
click() {}

2021-09-24 10:50 UTC, igr-ik commented on script.js
> +                    webix.message("validation is successful");
Думаю текст сообщения не не совсем верен. Не валидация успешная, а добавления элемента в таблицу, прошло успешно

2021-09-24 10:50 UTC, igr-ik commented on script.js
> +            click:function(){
Здесь тоже, и по всему коду во всех объектах, используй такой синтаксис methodName() { ... }, вместо methodName: function() { ... }, бывают случаи когда нужно стрелочную функцию использовать methodName: () => { ... }

2021-09-24 10:50 UTC, igr-ik commented on script.js
> +                    function(){
Здесь не принципиально, но тоже можно использовать стрелочную функцию

2021-09-24 10:50 UTC, igr-ik commented on script.js
> +                    function(){
И здесь, получится немного короче
() => webix.message("Rejected")

2021-09-24 10:50 UTC, igr-ik commented on script.js
> +        rating:function(value){ return value > 0; },
Вот здесь прям хорошо напрашиваются стрелочные функции, для краткости и изящности
year: value => value>1970 && value <(new Date()).getFullYear(),
votes: value => value>0 && value < 100000,
rating: value => value > 0

2021-09-24 10:50 UTC, igr-ik commented on script.js
> +    // position:"center",
Подчищай такие комменты перед коммитом. Как правило тебе это может уже никогда не пригодиться, но при этом код засоряется излишними комментами. А если вдруг понадобится, то у гита есть история, он помнит все изменения, и всегда что-то можно вернуть

2021-09-24 10:50 UTC, igr-ik commented on style.css
> +    background:transparent;
Сначала задаешь цвет для background, потом делаешь его прозрачным. Что-то из этого лишнее, судя по коду это - background-color:rgb(101, 118, 133);

2021-09-24 10:50 UTC, igr-ik commented on style.css
> +    background-color:rgb(238, 238, 238);
В форматировании кода, старайся придерживаться единого стиля, как в css так и в js. 
Где-то у тебя стоит пробел, после ":"
text-align: center
а где-то нет
background-color:rgb(238, 238, 238)

Рекомендую всегда добавлять пробел после ":", код выглядит красивее и легче читать. К тому же в проектах будут использовать линтеры, они на это ругаются. Привыкай сразу к нормальному форматированию кода

2021-09-26 09:25 UTC, MaksimKuzur reviewed
made adjustments to lesson 2

2021-09-26 09:32 UTC, MaksimKuzur commented on script.js
> +    width:250,
исправил

2021-09-26 09:32 UTC, MaksimKuzur commented on script.js
> +        { view:"text", label:"Title", name:"title", invalidMessage:"“title“ must be filled in" },
исправил

2021-09-26 09:32 UTC, MaksimKuzur commented on script.js
> +            view:"fieldset",
исправил

2021-09-26 09:32 UTC, MaksimKuzur commented on script.js
> +                if($$("formInputElements").validate()){
исправил

2021-09-26 09:32 UTC, MaksimKuzur commented on script.js
> +            y:40
исправил

2021-09-26 09:34 UTC, MaksimKuzur commented on script.js
> +    move:true,
взял из примера https://snippet.webix.com/ehbofg5m на 14 слайде презентации, вижу что нету смысла, исправил

2021-09-26 09:34 UTC, MaksimKuzur commented on script.js
> +            click:function() {
исправил

2021-09-26 09:35 UTC, MaksimKuzur commented on script.js
> +                    webix.message("validation is successful");
в задании прописано "If form data is valid, it should be added to the datatable. In addition, show a simple message to indicate that **validation is successful**", но согласен с тобой - исправил

2021-09-26 09:36 UTC, MaksimKuzur commented on script.js
> +            click:function(){
исправил

2021-09-26 09:36 UTC, MaksimKuzur commented on script.js
> +                    function(){
исправил

2021-09-26 09:36 UTC, MaksimKuzur commented on script.js
> +                    function(){
исправил

2021-09-26 09:36 UTC, MaksimKuzur commented on script.js
> +        rating:function(value){ return value > 0; },
исправил

2021-09-26 09:36 UTC, MaksimKuzur commented on script.js
> +    // position:"center",
исправил

2021-09-26 09:36 UTC, MaksimKuzur commented on style.css
> +    background:transparent;
исправил

2021-09-26 09:36 UTC, MaksimKuzur commented on style.css
> +    background-color:rgb(238, 238, 238);
исправил

2021-09-26 16:41 UTC, igr-ik approved these changes

2021-09-26 19:23 UTC, HelgaListopad approved these changes

2021-09-26 19:23 UTC, merged