lesson3 task done
MaksimKuzur/webix-start pull request #3
Opened 2021-09-27 19:11 UTC by MaksimKuzur

2021-09-28 07:50 UTC, igr-ik commented on grid_data.js
> +                {"id":1,"rank":"1"}
id одинаковые

2021-09-28 07:50 UTC, igr-ik commented on script.js
> +        { id: "id", header: "", css: "id", width: 50},
css: "id"
очень странное название для css класса

2021-09-28 07:50 UTC, igr-ik commented on script.js
> +        "wxi-trash": function(e, id) {
Плохая идея привязывать обработчик клика к названию иконки "wxi-trash", может возникнуть ситуация, когда нужно будет заменить на другую иконку, тогда тебе нужно будет не забывать заменить и в обработчике названия. Лучше по возможности создавать свой класс, например "on_click_delete" или "onClickDelete", и уже через него навешивать обработчик, в этом случае он будет независим от иконки.

2021-09-28 07:50 UTC, igr-ik commented on script.js
> +                "wxi-close": function(e, id) {
Здесь такая же ситуация с обработчиком, лучше через свой класс навешивать его

2021-09-28 07:50 UTC, igr-ik commented on script.js
> +const tree =  {
Снова проблемы с именование.
tree - дерево... Какое дерево? Дерево чего?
По коду ниже понимаю что эта таблица с продуктами. Правильнее и понятнее будет назвать productsTable

Пройдись по коду, посмотри все свои именования переменных, и не смотря на их присвоения, попробуй ответить себе на вопрос, что в них хранится!? 
Не всегда есть возможность сразу видеть что присваивается в переменную, и если название ее не понятное, приходится искать в коде ее присвоение, что замедляет чтение кода.
Это касается не только переменных, но и названия классов (как js, так и css), айдишек и всего остального.

2021-09-28 07:50 UTC, igr-ik commented on script.js
> +                        listTop.addCss(listTop.data.order[i], "top_list");
Через scheme это не получается сделать?

2021-09-28 07:50 UTC, igr-ik commented on script.js
> +    $$("list").filter(function(obj) {
$$("list").filter(obj => obj.name.toLowerCase().indexOf(value) !== -1);

Так же $$("list") лучше присвоить в переменную за обработчиком, чтобы каждый раз при срабатывании "onTimedKeyPress" не приходилось искать компонент "list".

2021-09-28 08:49 UTC, HelgaListopad commented on script.js
> +                        listTop.addCss(listTop.data.order[i], "top_list");
В схеме нет возможности красиво достать индекс, поэтому доставать первые пять элементов лучше после того, как всё загружено (при загрузке схема обрабатывает каждый айтем по мере их поступления в стор - нет информации об общем массиве данных или соседних элементах)

В целом, в этом задании применить подобную логику один раз после загрузки (`ready`) было бы достаточным решением (_так я бы и советовала сделать_).

P.S.
Если хочется, чтобы любые "первые пять" всегда имели определённый стиль независимо от сортировки/фильтрации, то лучше бы использовать не onAfterRender (слишком часто вызывается при ресайзе компонента), а другие события, имеющие отношение к работе с данными - например, то же свойство `ready` + события DataStore (`list.data`): [onAfterFilter](https://docs.webix.com/api__datastore_onafterfilter_event.html) и [onAfterSort](https://docs.webix.com/api__datastore_onaftersort_event.html)
События DataStore привязыва.тся на компонент следующим образом (в лекциях этого не было)
1. `list.data.attachEvent("EventName", highlightRows)`
2. через `on`:
```js
on:{
   "data->EventName": highlightRows
}
```

2021-09-28 09:03 UTC, HelgaListopad requested changes
Упущена часть задания:
> Enable data editing via Form. This short tutorial may help you: 
https://webix.com/tutorials/intro/1 

Если ранее через форму только добавлялись новые записи, тут в дополнение к этому должна появиться возможность редактировать выбранную в таблице
Вот нужная часть туториала
https://webix.com/tutorials/intro/11

Также предусмотри очистку формы/валидации, если ты удаляешь из таблицы строку, поля которой сейчас открыты в форме

2021-09-28 09:03 UTC, HelgaListopad commented on grid_data.js
> +                {"id":1,"rank":"1"}
Этот массив не используется нигде в коде, поэтому лучше удалить
Но да, подобных данных в коде быть не должно

2021-09-28 09:03 UTC, HelgaListopad commented on script.js
> +$$("treetable").openAll();
Эти два метода (`select`, `openAll`) лучше перенести в `ready` компонентов, к которым они имеют отношение
Причины:
1. Если бы данные шли с сервера, то обязательно нужно было бы дождаться их загрузки (иначе селектить и открывать в этот момент может быть ещё нечего)
2. Читабельность/доступность кода: не ожидаешь, что то, что простые методы работы с данными будут заданы так далеко от кода компонента

2021-09-28 09:03 UTC, HelgaListopad commented on script.js
>      autoConfig: true,
Можно убрать за ненадобностью - колонки теперь заданы вручную

2021-09-28 09:03 UTC, HelgaListopad commented on script.js
> +        { id: "title", header: ["Film title", {content:"textFilter"}], width: 200, sort: "string"},
Вместо `width` для этой колонки лучше задать `fillspace`, чтобы таблица не выглядела мелкой

2021-09-28 09:23 UTC, HelgaListopad commented on script.js
> +    scroll: "auto",
Такое значение не поддерживается treetable
Но это косяк в нашей доке и примерах - будем исправлять

2021-09-28 09:24 UTC, HelgaListopad commented on script.js
> +    view: "treetable",
Не хватает по заданию правильного режима select:
> Enable cell selection

2021-09-29 16:11 UTC, MaksimKuzur commented on grid_data.js
> +                {"id":1,"rank":"1"}
исправлено, не используемый массив удален

2021-09-29 16:21 UTC, MaksimKuzur commented on script.js
> +        { id: "id", header: "", css: "id", width: 50},
исправлено

2021-09-29 18:19 UTC, MaksimKuzur commented on script.js
> +        "wxi-trash": function(e, id) {
исправлено

2021-09-29 18:19 UTC, MaksimKuzur commented on script.js
> +                "wxi-close": function(e, id) {
исправлено

2021-09-29 19:27 UTC, MaksimKuzur commented on script.js
> +const tree =  {
исправлено

2021-09-29 20:18 UTC, MaksimKuzur commented on script.js
> +    $$("list").filter(function(obj) {
исправлено

2021-09-29 22:56 UTC, MaksimKuzur commented on script.js
> +                        listTop.addCss(listTop.data.order[i], "top_list");
исправлено

2021-09-29 22:56 UTC, MaksimKuzur commented on script.js
> +$$("treetable").openAll();
исправлено

2021-09-29 22:56 UTC, MaksimKuzur commented on script.js
>      autoConfig: true,
исправлено

2021-09-29 22:56 UTC, MaksimKuzur commented on script.js
> +        { id: "title", header: ["Film title", {content:"textFilter"}], width: 200, sort: "string"},
исправлено

2021-09-29 22:57 UTC, MaksimKuzur commented on script.js
> +    scroll: "auto",
исправлено

2021-09-29 22:57 UTC, MaksimKuzur commented on script.js
> +    view: "treetable",
исправлено

2021-09-30 09:09 UTC, HelgaListopad approved these changes

2021-09-30 10:01 UTC, igr-ik commented on script.js
> +    ready: function() {
Не используй "function" в методах объекта, это делается проще
{
...,
ready() { ... },
...
}

2021-09-30 10:01 UTC, igr-ik commented on script.js
> +        const form = $$("formForDataFilms");
Правильнее было бы вынести получение и сохранения формы в константу перед if

const form = $$("formForDataFilms");
if(form.validate()) {}

Иначе получается что ты два раза делаешь поиск формы.

2021-09-30 10:01 UTC, igr-ik commented on script.js
> +    const item_id = films.getSelectedId();
Придерживайся единого стиля именования переменных и констант. Почти везде у тебя через camelCase, а здесь почему-то через нижнее подчеркивание.

2021-09-30 10:01 UTC, igr-ik commented on script.js
> +                const listTop = $$("listUsers");
Забыл подправить названия константы под названия компонента "listUsers"
const listUsers = $$("listUsers");

2021-09-30 10:01 UTC, igr-ik commented on script.js
> +                for (let  i = 0; i < (listTop.count() > 4 ? 5 : listTop.count()); i++ ) {
listTop.count() > 4 ? 5 : listTop.count()
Эту часть кода лучше сохранить в переменную перед циклом.

2021-09-30 10:01 UTC, igr-ik commented on script.js
> +    ready: function() {
ready() { ... }

2021-09-30 16:25 UTC, MaksimLakatkouOld commented on script.js
> +    ready: function() {
исправлено

2021-09-30 16:25 UTC, MaksimKuzur commented on script.js
> +        const form = $$("formForDataFilms");
исправлено

2021-09-30 16:25 UTC, MaksimKuzur commented on script.js
> +    const item_id = films.getSelectedId();
исправлено

2021-09-30 16:26 UTC, MaksimKuzur commented on script.js
> +                const listTop = $$("listUsers");
исправлено

2021-09-30 16:26 UTC, MaksimKuzur commented on script.js
> +                for (let  i = 0; i < (listTop.count() > 4 ? 5 : listTop.count()); i++ ) {
исправлено

2021-09-30 16:26 UTC, MaksimKuzur commented on script.js
> +    ready: function() {
исправлено

2021-10-01 06:58 UTC, igr-ik approved these changes

2021-10-01 07:01 UTC, merged