Lesson4
MaksimKuzur/webix-start pull request #4
Opened 2021-09-30 07:41 UTC by MaksimKuzur

lesson4 task done

2021-09-30 10:33 UTC, HelgaListopad requested changes

2021-09-30 10:33 UTC, HelgaListopad commented on script.js
> +function deleteItem() {
`remove` лучше позволять вызывать из одного места в интерфейсе - у тебя уже есть иконка в строках, её и стоит оставить
Кнопку и этот метод я бы предложила удалить

2021-09-30 10:33 UTC, HelgaListopad commented on script.js
>          { view: "text", label: "Category", name: "category" },
Это поле не отображается в таблице, сейчас там есть только `categoryId`
Если добавлять для него сейчас инпут в форме, то это должен быть
- любой селект (в качестве value у него будет ID выбранной опции)
- в нём должны быть те же опции, что в коллекции колонки

2021-09-30 10:33 UTC, HelgaListopad commented on script.js
> +        const itemData = form.getValues();
На этом этапе задание меняется: 
> Remove logic of form and datatable interaction (setValues, update/add item).
Bind a form to datatable.
Edit datatable via the bound form. 

Я вижу, что `bind` ты вызываешь в конце этого файла, но он не используется для редактирования данных.

До этого ты писало логику апдейта и добавления сам, теперь же, когда этот этап пройден, следует заменить твой код на data binding
При вызове `form.save()` в этом случае вебикс сам будет решать на основании selection, добавлять новый айтем или обновить существующий (выбранный сейчас)

2021-09-30 10:33 UTC, HelgaListopad commented on script.js
> +            data: users
Когда мы синхронизируем чарт с листом, своей data у него уже не будет - нужно удалить

2021-09-30 10:33 UTC, HelgaListopad commented on script.js
> +    });
Сейчас, когда ты сортируешь лист, данные в чарте начинают "скакать", меняясь местами
Это происходит потому, что при каждой сортировке из листа в чарт поступает тот же набор данных, но в другом порядке - соответственно, группировка обрабатывает их в другой последовательности.
Чтобы избежать этой проблемы, после группировки чарт можно отсортировать по любому существующему после группировки полю (например, id или country)

2021-09-30 10:45 UTC, igr-ik commented on script.js
> +        const form = $$("formForDataFilms");
Вынеси перед if

2021-09-30 10:45 UTC, igr-ik commented on script.js
> +                        $$("listUsers").add({ name: (userRandom[randomInt(1, 5)]).value, age:randomInt(1, 90), country:(countryRandom[randomInt(1, 5)]).value })
Написал код в одну строку, и читать стало сразу трудней

2021-09-30 10:45 UTC, igr-ik commented on script.js
> +                $init: function(obj) {
$init(obj) { ... }

2021-09-30 10:45 UTC, igr-ik commented on script.js
> +                    obj.$css = "user_young_highlight";
Старайся всегда оборачивать код в фигурные скобки, даже если одна строка кода
if(obj.age < 26) {
    obj.$css = "user_young_highlight";
}

2021-09-30 10:45 UTC, igr-ik commented on script.js
> +        let year = value;
Не понятно для чего ты это сделал. Можешь в параметрах метода compare, назвать параметр year вместо value.
compare(year, filter, item) { ... }

2021-09-30 10:45 UTC, igr-ik commented on script.js
> +        getValue: function(node){
getValue: node => node.getValue()

2021-09-30 10:45 UTC, igr-ik commented on script.js
> +        setValue: function(node, value){
setValue(node, value) {
            node.setValue(value);
        }

2021-09-30 22:07 UTC, MaksimKuzur commented on script.js
> +function deleteItem() {
исправлено

2021-09-30 22:07 UTC, MaksimKuzur commented on script.js
>          { view: "text", label: "Category", name: "category" },
исправлено

2021-09-30 22:07 UTC, MaksimKuzur commented on script.js
> +        const itemData = form.getValues();
исправлено

2021-09-30 22:07 UTC, MaksimKuzur commented on script.js
> +            data: users
исправлено

2021-09-30 22:07 UTC, MaksimKuzur commented on script.js
> +    });
исправлено

2021-09-30 22:08 UTC, MaksimKuzur commented on script.js
> +        const form = $$("formForDataFilms");
function saveItem() больше не нужна, поэтому удалена

2021-09-30 22:08 UTC, MaksimKuzur commented on script.js
> +                        $$("listUsers").add({ name: (userRandom[randomInt(1, 5)]).value, age:randomInt(1, 90), country:(countryRandom[randomInt(1, 5)]).value })
исправлено

2021-09-30 22:08 UTC, MaksimKuzur commented on script.js
> +                $init: function(obj) {
исправлено

2021-09-30 22:08 UTC, MaksimKuzur commented on script.js
> +                    obj.$css = "user_young_highlight";
исправлено

2021-09-30 22:08 UTC, MaksimKuzur commented on script.js
> +        let year = value;
исправлено

2021-09-30 22:08 UTC, MaksimKuzur commented on script.js
> +        getValue: function(node){
исправлено

2021-09-30 22:08 UTC, MaksimKuzur commented on script.js
> +        setValue: function(node, value){
исправлено

2021-10-01 07:06 UTC, igr-ik approved these changes

2021-10-01 07:48 UTC, HelgaListopad requested changes

2021-10-01 07:48 UTC, HelgaListopad commented on script.js
> +                $$("formForDataFilms").save()
Валидацию перед сохранением лучше не терять

2021-10-01 08:31 UTC, MaksimKuzur commented on script.js
> +                $$("formForDataFilms").save()
валидацию вернул

2021-10-01 08:36 UTC, MaksimKuzur commented on script.js
> +                $$("formForDataFilms").save()
вернул валидацию

2021-10-01 10:01 UTC, HelgaListopad approved these changes

2021-10-01 14:30 UTC, merged